version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - .env