name: Unit tests

on:
  pull_request:
    branches: [ main ]

jobs:

  unit_test_go:
    name: Go unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.3

      - name: Run unit tests
        run: go test -v ./...
